authenticate:
  lore: "§6Authentifié par %authority% (%type%)"

tab:
  # MiniMessage format and PAPI placeholders allowed
  header: <bold><gradient:#FF8C42:#F9C784>La Boulangerie</gradient></bold>
  name: "<papi:luckperms_meta_prefixtab> <papi:player_name> <papi:player_colored_ping>"
  footer: "<papi:lands_land_role>\n
    <papi:lands_land_name> <papi:lands_nation_name>\n
    <color:#4E598C>mc.laboulangerie.net</color>\n
    <#E4D9FF><papi:lbcore_date_full><papi:img_hourglass>"

nametag:
  - <papi:luckperms_meta_prefixtab>[<papi:lbmmo_palier_colored>] <gray><papi:player_name>
  - <papi:lbcore_eastereggs_worldguard>

links:
  discord: https://laboulangerie.net/discord
  youtube: https://www.youtube.com/channel/UCrIHI9-q9b8MGUgU6UGuclg
  wiki: https://laboulangerie.fandom.com/fr/wiki/Wiki_La_Boulangerie
  twitter: https://twitter.com/BoulangerieMc
  github: https://github.com/LaBoulangerie
  rules: https://laboulangerie.net/rules
  map: https://laboulangerie.net/map
  librahost: https://librahost.fr

misc:
  declined-pack-kick-msg: "<red>Veuillez accepter le pack de ressources pour jouer s'il vous plaît !"

eastereggs:
  # You can edit all the message of the plugin here.
  messages:
    console: §4The command only can be used by a player.
    added: §aEasterEgg successfully added.
    deleted: §cEasterEgg successfully deleted.
    permission: §cYou don't have permission to execute this command.
    utilization: "§cError: §e/easteregg help§a."
    not-existing: §cThis easteregg doesn't existing.
    not-head: §cYou need to have a head on your front.
    eggs-found: |-
      §aEastereggs:
      §bVous avez trouvé §e%amount%§a/§e%total% §beastereggs
    validated-title:
      - §2Nouveau Easter Egg!
      - §7(§a%amount%§7/§e%max-amount%§7)
    already-validated: §cVous avez déjà trouvé cet easteregg.
    help:
      - §e-------------{ §3EasterEggs §e}-------------
      - "§f/eegg set|add§7: §aCommmand to make a player head was an easteregg."
      - "§f/eegg remove|delete§7: §aCommmand to remove an easteregg."
      - "§f/eegg help§7: §aCommmand to show this page."

  settings: {}
first-join-commands: {}

calendar:
    months:
        - "Gaiarkhè"
        - "Tempopidum"
        - "Quinésil"
        - "Éposendre"

# Use BARRIER for any blocks
# Top to bottom priority
speed-paths:
  grasspath:
    speed: 0.4
    blocks:
      - DIRT_PATH
  amethystpath:
    speed: 0.6
    blocks:
      - BARRIER
      - AMETHYST_BLOCK
#resource-pack-url: https://laboulangerie.net/share/BreadDough/141bbd2.zip
#resource-pack-sha1: fe89c4045cc7006baf95b135ffe661bf43c27aa8

# Items which are results of crafting recipes
# that should be disabled
disabled-crafts:
  - VEX_ARMOR_TRIM_SMITHING_TEMPLATE
  - WILD_ARMOR_TRIM_SMITHING_TEMPLATE

vault-reset-regions:
  - world:vault_reset_area

rp-radius: 10

rp-cooldown: 15 # in seconds