name: LaBoulangerieCore
version: ${project.version}
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: 1.17
authors: [Grooble_, PainOchoco, Blackoutburst, Pikachuz3]
depend: [Towny, LuckPerms]
softdepend: [PlaceholderAPI, LaBoulangerieMmo]
commands:
    authenticate:
        permission: laboulangerie.authenticate
        description: Authenticate an item
        usage: /authenticate [player|nation|town]
    wiki:
        description: Sends the wiki link
    discord:
        description: Sends the discord link
    youtube:
        description: Sends the youtube link
    twitter:
        description: Sends the twitter link
    github:
        description: Sends the github link
    map:
        description: Sends the map link
    pointsdivins:
        description: Voir ses points divins
    reloadnametag:
        description: Recharge les nametag des joueurs
permissions:
    laboulangeriecore.*:
        default: op
        children:
            - laboulangeriecore.authenticate
    laboulangeriecore.authenticate:
        default: op
    laboulangeriecore.divinepoints.admin:
        default: op
    laboulangeriecore.nametag.admin:
        default: op
    laboulangeriecore.advancement.debug:
        default: op
