name: LaBoulangerieCore
version: ${project.version}
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: 1.17
authors: [Grooble_, PainOchoco, Blackoutburst]
depend: [Towny, LuckPerms]
softdepend: [PlaceholderAPI]
commands:
    authenticate:
        permission: laboulangerie.authenticate
        description: Authenticate an item
        usage: /authenticate [player|nation|town]
    wiki:
        description: Sends the wiki link
    discord:
        description: Sends the discord link
    youtube:
        description: Sends the youtube link
    twitter:
        description: Sends the twitter link
    github:
        description: Sends the github link
    map:
        description: Sends the map link
    faveursdivines:
        description: Voir ses faveurs divines
    housewand:
        description: Donne l'outils de creation de maison de nation
        permission: laboulangeriecore.house.admin
    createhouse:
        description: Créer une maison de nation
        permission: laboulangeriecore.house.admin
    listhouse:
        description: Liste les maisons de nation
        permission: laboulangeriecore.house.admin
    deletehouse:
        description: Supprime une maisons de nation
        permission: laboulangeriecore.house.admin
    nationhouses:
        description: Manage nation houses
        permission: laboulangeriecore.house.admin
        usage: /nationhouses [list|create|delete] ([free|occupied] | <id>)
    reloadnametag:
        description: Recharge les nametag des joueurs
permissions:
    laboulangeriecore.*:
        default: op
        children:
            - laboulangeriecore.authenticate
            - laboulangeriecore.divinefavors.admin
            - laboulangeriecore.house.admin
            - laboulangeriecore.nametag.admin
    laboulangeriecore.authenticate:
        default: op
    laboulangeriecore.divinefavors.admin:
        default: op
    laboulangeriecore.house.admin:
        default: op
    laboulangeriecore.nametag.admin:
        default: op
