name: LaBoulangerieCore
version: ${project.version}
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: 1.17
authors: [Grooble_, PainOchoco]
depend: [Towny]
softdepend: [PlaceholderAPI]
commands:
    authenticate:
        permission: laboulangerie.authenticate
        description: Authenticate an item
        usage: /authenticate [player|nation|town]
    wiki:
        description: Sends the wiki link
    discord:
        description: Sends the discord link
    youtube:
        description: Sends the youtube link
    twitter:
        description: Sends the twitter link
    github:
        description: Sends the github link
    map:
        description: Sends the map link
permissions:
    laboulangeriecore.*:
        default: op
        children:
            - laboulangeriecore.authenticate
    laboulangeriecore.authenticate:
        default: op
