name: LaBoulangerieCore
version: 1.2.0
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: "1.21"
authors: [Grooble_, PainOchoco, Blackoutburst, Pikachuz3, Herllox, Grôle, Red69_Leaf]
depend: [LuckPerms, ProtocolLib]
softdepend: [PlaceholderAPI, QuickShop, WorldGuard, BetonQuest, Gringotts]
commands:
    authenticate:
        permission: laboulangerie.authenticate
        description: Authenticate an item
        usage: /authenticate [player|nation|land]
    wiki:
        description: Sends the wiki link
    youtube:
        description: Sends the youtube link
    twitter:
        description: Sends the twitter link
    github:
        description: Sends the github link
    librahost:
        description: Our beloved LibraHost
    easteregg:
        description: Main command for the easteregg part
        aliases: [eegg]
        permission: laboulangeriecore.admin
    core:
        description: Admin commands for the plugin
        usage: /core reload|conversion
        aliases: [lcore]
        permission: laboulangeriecore.admin
    seen:
        description: Details on players' connection
        usage: /seen [Player]
        permission: laboulangeriecore.seen
    speed:
        description: Toggle speed paths
        usage: /speed
    realname:
        description: Get the real name of a player
        usage: /realname <nickname>
    hat:
        description: Put something on your head
        usage: /hat
    roll:
        description: Send a random number between 1 and <max> to nearby players
        usage: /roll <max>
        aliases: [r]
    wroll:
        description: Send a random number between 1 and <max> to all players
        usage: /wroll <max>
        aliases: [wr]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
    spyrp:
        description: Enable/disable all roll visiblity for the sender
        usage: /spyrp
        aliases: [sr]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
    me:
        description: Make a message in the chat that send the player's action to nearby players
        usage: /me [action]
    color:
        description: Affiche les 16 couleurs Minecraft
        usage: /color
permissions:
    laboulangeriecore.*:
        default: op
        children:
            - laboulangeriecore.authenticate
            - laboulangeriecore.admin
            - laboulangeriecore.seen
    laboulangeriecore.authenticate:
        default: op
    laboulangeriecore.admin:
        default: op
    laboulangeriecore.eeggs.admin:
        default: op
    laboulangeriecore.seen:
        default: op
    laboulangeriecore.elytra.bypass:
        default: op
    laboulangeriecore.ipverify:
        default: op
