name: LaBoulangerieCore
version: 1.1.2
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: "1.21"
authors: [Grooble_, PainOchoco, Blackoutburst, Pikachuz3, Herllox, Grôle]
depend: [Lands, LuckPerms, ProtocolLib, LaBoulangerieMmo]
softdepend: [PlaceholderAPI, BetonQuest, QuickShop]
commands:
    authenticate:
        permission: laboulangerie.authenticate
        description: Authenticate an item
        usage: /authenticate [player|nation|land]
    wiki:
        description: Sends the wiki link
    youtube:
        description: Sends the youtube link
    twitter:
        description: Sends the twitter link
    github:
        description: Sends the github link
    librahost:
        description: Our beloved LibraHost
    faveursdivines:
        description: Voir ses faveurs divines
    housewand:
        description: Donne l'outils de creation de maison de nation
        permission: laboulangeriecore.house.admin
    createhouse:
        description: Créer une maison de nation
        permission: laboulangeriecore.house.admin
    listhouse:
        description: Liste les maisons de nation
        permission: laboulangeriecore.house.admin
    deletehouse:
        description: Supprime une maisons de nation
        permission: laboulangeriecore.house.admin
    nationhouses:
        description: Manage nation houses
        permission: laboulangeriecore.house.admin
        usage: /nationhouses [list|create|delete] ([free|occupied] | <id>)
    houseshop:
        description: Houses of nations shop
        permission: laboulangeriecore.houseshop
        usage: /houseshop (sell)
    houseflag:
        description: Modify house flags
        permission: laboulangeriecore.house.admin
        usage: /houseflag <house> [list|add|remove] (<flag>)
    housemembers:
        description: Modify house members
        permission: laboulangeriecore.house.admin
        usage: /housemembers <house> [list|add|remove] (<member>)
    easteregg:
        description: Main command for the easteregg part
        aliases: [eegg]
        permission: laboulangeriecore.admin
    core:
        description: Admin commands for the plugin
        usage: /core reload|conversion
        aliases: [lcore]
        permission: laboulangeriecore.admin
    spawn:
        description: Go to spawn
        usage: /spawn
    seen:
        description: Details on players' connection
        usage: /seen [Player]
        permission: laboulangeriecore.seen
    event:
        description: Main command for the event assistant
        permission: laboulangeriecore.eventassistant
        usage: /event [name] <start|stop|nextStep|run|goTo|status> ([stepName])
    speed:
        description: Toggle speed paths
        usage: /speed
    realname:
        description: Get the real name of a player
        usage: /realname <nickname>
    hat:
        description: Put something on your head
        usage: /hat
    roll:
        description: Send a random number between 1 and <max> to nearby players
        usage: /roll <max>
        aliases: [r]
    wroll:
        description: Send a random number between 1 and <max> to all players
        usage: /wroll <max>
        aliases: [wr]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
    spyrp:
        description: Enable/disable all roll visiblity for the sender
        usage: /spyrp
        aliases: [sr]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
    me:
        description: Make a message in the chat that send the player's action to nearby players
        usage: /me [action]
    narration:
        description: Make a message in the chat that send a narration text to nearby players
        usage: /narration [narration]
        aliases: [nar, nr]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
    wnarration:
        description: Make a message in the chat that send a narration text to all players
        usage: /wnarration [narration]
        aliases: [wnar, wnr]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
    consequence:
        description: Send a consequence text to a player
        usage: /consequence [player] [narration]
        aliases: [cons, c]
        permission: laboulangeriecore.admin
        permission-message: You do not have <permission>
permissions:
    laboulangeriecore.*:
        default: op
        children:
            - laboulangeriecore.authenticate
            - laboulangeriecore.divinefavors.admin
            - laboulangeriecore.house.admin
            - laboulangeriecore.admin
            - laboulangeriecore.houseshop
            - laboulangeriecore.seen
            - laboulangeriecore.eventassistant
    laboulangeriecore.authenticate:
        default: op
    laboulangeriecore.divinefavors.admin:
        default: op
    laboulangeriecore.house.admin:
        default: op
    laboulangeriecore.admin:
        default: op
    laboulangeriecore.houseshop:
        default: op
    laboulangeriecore.eeggs.admin:
        default: op
    laboulangeriecore.seen:
        default: op
    laboulangeriecore.eventassistant:
        default: op
