name: LaBoulangerieCore
version: ${project.version}
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: 1.17
authors: [Grooble_]
depend: []
softdepend: [PlaceholderAPI]
permissions:
    laboulangeriecore.*:
        default: op