name: LaBoulangerieCore
version: ${project.version}
main: net.laboulangerie.laboulangeriecore.LaBoulangerieCore
api-version: 1.17
authors: [Grooble_, PainOchoco]
depend: [Towny]
softdepend: [PlaceholderAPI]
commands:
    authenticate:
        permission: laboulangerie.authenticate
        description: Authenticate an item
        usage: /authenticate [player|nation|town]
permissions:
    laboulangeriecore.*:
        default: op
        children:
            - laboulangeriecore.authenticate
    laboulangeriecore.authenticate:
        default: op
