name: LaBoulangerieCore continuous delivery

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: JDk 21 setup
              uses: actions/setup-java@v1
              with:
                java-version: 1.21
            - uses: actions/cache@v4
              env:
                cache-name: cache-gradle
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                    .gradle/caches
                key: ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('*.gradle.kts', '**/gradle-wrapper.properties') }}
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: "8.11.1"
            - name: Compile
              run: ./gradlew assemble
            - name: Clean build outputs
              run: rm build/libs/LaBoulangerieCore-*dev*.jar
            - uses: actions/upload-artifact@v4
              with:
                name: laboulangeriecore
                path: build/libs/
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: laboulangeriecore
            - name: Clone Plugins Project
              run: |
                  git config --global user.name "octocroissant[bot]"
                  git config --global user.email 149737708+octocroissant[bot]@users.noreply.github.com
                  git config --global --add safe.directory "$GITHUB_WORKSPACE"
                  git clone https://octocroissant[bot]:${{ secrets.PAT_TOKEN }}@github.com/LaBoulangerie/Server.git
                  cp [!original-]**.jar Server/plugins/
                  cd Server
                  git add .
                  git commit -m "Update artifact from $GITHUB_REPOSITORY"
                  git push
